[package]
name = "donut-web"
version = "0.1.0"
authors = ["alugocp <alugocp@aim.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.48"
cfg-if = "0.1.9"
base64 = "0.10.1"
image = "0.21.0"
png = "0.14.1"
